### ISSUE TITLE
ECRへのプッシュスクリプトをCodeBuild上から実行出来るようにする

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-nuxt#13]
# Doneの定義
- 下記の記事のようにECRへのプッシュがCodeBuild上から実行出来るようになっている事

https://dev.classmethod.jp/tool/docker/20170225-codebuild-docker/

 # 補足情報
https://github.com/nekochans/qiita-stocker-backend/pull/185 で追加したファイル `push-ecr.sh` をCodeBuildのタスク内から実行する予定。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは8を想定しているよ🐱！（5でも大丈夫だと思うけど、一応初めての試みだしハマる可能性を考慮して）

**Comment by kobayashi-m42** [comment]
@keitakn 了解！8でいいと思う🐱

**Comment by keitakn** [comment]
@kobayashi-m42 
>了解！8でいいと思う🐱

確認ありがとう！

今気がついたけど作成するリポジトリを間違えた・・・🐱

https://github.com/nekochans/qiita-stocker-terraform に作り直すね！
