### ISSUE TITLE
ローカル用の.envrcの生成処理を作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-nuxt#14]
# Doneの定義
ローカル用の.envrcの生成処理する処理が作成されていること

**Comment by kobayashi-m42** [comment]
@keitakn パラメータストアは作成済みだから、ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で問題ないと思う🐱
