### ISSUE TITLE
自作定義したMiddlewareの型定義を追加する

### ISSUE THREAD

**Issue by keitakn** [nekochans/qiita-stocker-nuxt#21]
# Doneの定義
- https://github.com/nekochans/qiita-stocker-nuxt/pull/18 で作成したミドルウェアの型定義が追加されている事

 # 補足情報
Nuxtのデフォルトの型だとおそらく不十分なので独自拡張が必要かも。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは3くらいでどうだろう🐱？

**Comment by kobayashi-m42** [comment]
@keitakn うん！3でいいと思う！🐱課題の追加ありがとう！

**Comment by keitakn** [comment]
# めも
Nuxt.js 2.9以降に更新されていれば↓が使えそう🐱

https://typescript.nuxtjs.org/cookbook/middlewares.html

**Comment by kobayashi-m42** [comment]
@keitakn Nuxt.js 2.10にアップグレートしたことにより、独自で定義する必要がなくなったのでクローズ。
