### ISSUE TITLE
vuex-type-helperを導入する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-nuxt#27]
# Doneの定義
- vuex-type-helperを導入し、Vuexの型が定義されていること

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で問題ないと思う🐱！ただ、もう少し状況が進むと対応箇所が多くなるから、その場合はまたストーリーポイントの見直しをしても良いと思う！
