### ISSUE TITLE
セッション無効時のエラー処理を追加

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-nuxt#49]
# Doneの定義
- セッションが無効の場合、エラー画面が表示されること
- 保持されているセッションが削除され、ログアウト状態となっていること

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは3を想定しているよ🐱

**Comment by keitakn** [comment]
@kobayashi-m42 なるほど、うん！3で大丈夫だと思う🐱！
