### ISSUE TITLE
@nuxtjs/eslint-config-typescriptに置き換える

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-nuxt#59]
# Doneの定義
- @nuxtjs/eslint-config が @nuxtjs/eslint-config-typescriptに置き換えられ、Lintが実行できること

 # 補足情報
https://github.com/nuxt/eslint-config#typescript

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは3を想定しているよ🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！3で問題ないと思う🐱！
