### ISSUE TITLE
サイドメニューの全てのストック押下時の表示処理を追加

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-nuxt#70]
# Doneの定義
- `全てのストック`が押下された際に下記の動作を満たしていること
  - 全てのストックが表示されていること
  - `stocks/all` に遷移していること

**Comment by kobayashi-m42** [comment]
@keitakn ストーリーポイントは2を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！2で大丈夫だと思う🐱
