### ISSUE TITLE
スタイルの修正

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-nuxt#82]
# Doneの定義
- スマホで表示した際の余白を調整する

 # 補足情報
- ストック一覧を表示した際に、画面の左右に余白が表示されていないため修正を行う

**Comment by kobayashi-m42** [comment]
ストーリーポイントは3を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！3で大丈夫だと思う🐱
