### ISSUE TITLE
不要なfaviconを削除する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-nuxt#91]
# Doneの定義
- 不要なリソースが削除されていること
`/static`配下のfavicon

**Comment by kobayashi-m42** [comment]
@keitakn 不要なリソースが残っていたので削除するね！ポイントは1で問題ないかな？🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！1で大丈夫だと思う🐱👌
