### ISSUE TITLE
バイナリメディアタイプの設定を削除する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/qiita-stocker-nuxt#93]
# Doneの定義
- API Gatewayのバイナリメディアタイプの設定が削除されていること
- aws-serverless-expressのcreateServerで指定しているbinaryMimeTypesの設定が削除されていること

**Comment by kobayashi-m42** [comment]
@keitakn ポイントは、動作確認を含めて3を想定🐱

**Comment by keitakn** [comment]
@kobayashi-m42 作成ありがとう🐱！3で問題ないと思う👍
